export const actions = {
  ADD_NEW_NOTE: "ADD_NEW_NOTE",
  ON_HANDLE_MODAL: "ON_HANDLE_MODAL",
  EDIT_NOTE: "EDIT_NOTE",
  ON_SET_CURRENT_EDIT_NOTE: "ON_SET_CURRENT_EDIT_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
  ON_SEARCH_NOTE: "ON_SEARCH_NOTE",
  ADD_NEW_ELEMENT: "ADD_NEW_ELEMENT",
  DELETE_ELEMENT: "DELETE_ELEMENT",
};
